### ISSUE TITLE
References for substructure search methodology

### ISSUE THREAD

**Issue by enricogandini** [chembl/FPSim2#105]
Could you please recommend any references on the use of the approximate substructure search that is implemented in FPSim2, based on the Tversky metric and on the RDKit Pattern Fingerprint?

I read both the [FPSim2 documentation](https://chembl.github.io/FPSim2/source/user_guide/subs.html) and the [RDKit documentation](https://www.rdkit.org/docs/source/rdkit.Chem.rdmolops.html#rdkit.Chem.rdmolops.PatternFingerprint) on the pattern fingerprint, but I haven't found any reference. Am I missing something?

I would like references explaining how this approximate method compares to full substructure searches.
In particular, I am interested in knowing:

- is stereochemistry considered in any way in the approximate method?
- is the approximate method more biased to false positives or false negatives? The set produced by an approximate substructure search will mostly include compounds that are not real substructure matches, and should be discarded by an additional full substructure search? Or will the approximate search exclude a lot of compounds that a full search would have retrieved?

I would be grateful if you could provide any reference!

**Comment by eloyfelix** [comment]
Hi, this blogpost from @greglandrum should hopefully help a bit: http://rdkit.blogspot.com/2013/11/fingerprint-based-substructure.html
