### ISSUE TITLE
Faced an Error while running with n_workers=70

### ISSUE THREAD

**Issue by Bibyutatsu** [chembl/FPSim2#33]
File "/opt/conda/lib/python3.7/site-packages/FPSim2/FPSim2.py", line 193, in _parallel_run                                                  
    c_indexes = [[x, x + chunk_size] for x in range(i_start, i_end, chunk_size)]                                                              
ValueError: range() arg 3 must not be zero

**Comment by eloyfelix** [comment]
hi, I'll look on this but it probably happened because there were more threads than molecules to search! Using 70 workers is probably generating more overhead than anything else... 
Wouldn't use more than 2-4 workers per core.
