### ISSUE TITLE
Tversky similarity

### ISSUE THREAD

**Issue by taryep** [chembl/FPSim2#35]
Could you add the Tversky similarity and the choice of alpha and beta coefficients in arguments ? 
I’m actually doing this using RDKit and jupyter notebooks, but with FPSim 2 it would be faster and take less RAM.

**Comment by eloyfelix** [comment]
I can be added and we'll probably do. Thanks for the suggestion.

**Comment by eloyfelix** [comment]
it's now implemented in this branch: https://github.com/chembl/FPSim2/tree/tversky

still needs some little work before merging and creating new conda builds

**Comment by eloyfelix** [comment]
this functionality is now available in version 0.1.8

`results = fpe.tversky(query, threshold=0.7, a=0.5, b=0.5)`
