### ISSUE TITLE
FPSim only supports integer ids for molecules

### ISSUE THREAD

**Issue by metma99** [chembl/FPSim2#59]
Hello all:
I installed the latest version of FPSim2 on Centos 7 and tried to create a db.
However, I am not able to use the vendor's provided name for mol_id_prop.
Is it possible to allow strings in id?
Best,
Markus

**Comment by eloyfelix** [comment]
Hi Markus,

It is not possible to currently use non integer id's and it's not planned to allow them in short.

**Comment by eloyfelix** [comment]
closing this for now as this is not currently in our plans
