### ISSUE TITLE
FPSim2Cuda.py - "list index out of range"

### ISSUE THREAD

**Issue by JanoschMenke** [chembl/FPSim2#71]
Hey I am running a for-loop over multiple queries
However, for some Queries the `FPSIM2Cuda.py` throws the Error `List index out of errors` 

And it points to this line:
`subset_size = int(fp_range[1] - fp_range[0])`
 
For other queries is works just fine.
Do you know what could cause the error

**Comment by eloyfelix** [comment]
Glad to hear that there is people using the GPU functionality :) 

After excluding compounds that won't make the threshold there are no remaining compounds to run. It means that compounds that crash are compounds that will not find any similar compound above your threshold.

This shouldn't be happening if using CPU (it's sorted there).

I'll check it and try to release a new version over the weekend.

**Comment by JanoschMenke** [comment]
Are you serious? The GPU functionality is awesome :)
Okay thanks for the explanation. Then a `try` will do the trick

**Comment by eloyfelix** [comment]
thanks for reporting and for your feedback! 
New release is out so as soon as conda-forge building system spots the new version we'll have a new version in the repository.
