### ISSUE TITLE
Similarity Search  with Bitvector rather than SMILES as Query? 

### ISSUE THREAD

**Issue by JanoschMenke** [chembl/FPSim2#73]
Hi I was just wondering how one would go about performing a similarity search, when the queries Smiles is not known. So I only have the array of bits. As long as the length of the array is the same as the `molecules I want to screen through this should work, right?

In you code I find it difficult to find where exactly the conversion from Smiles string to Vector takes place. Bc I guess that's where I would have to start.

**Comment by eloyfelix** [comment]
#99 is now merged

**Comment by JanoschMenke** [comment]
Awesome thank you very much.
