### ISSUE TITLE
Conda cant f

### ISSUE THREAD

**Issue by nima17** [chembl/FPSim2#93]
Hi,
I tried running conda install -c conda-forget fpmsim2

but I get an error saying that fpmsim2 cant be found from current channels.
Current channels:   - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

**Comment by eloyfelix** [comment]
Hi, the correct command is:

```
conda install -c conda-forge fpsim2
```

or

```
pip install fpsim2
```
if using pip
